### PR TITLE
Think I've solved the troll_counting problem

### PR DESCRIPTION
**Pull request by conference-student**
@andrewcharlton - I think I've solved the problem

### CODE REVIEW

**Comment by andrewcharlton** [comment]
@conference-student Why is your code not recognising numbers greater than 8 should be 'lots'?

**Comment by conference-student** [comment]
Numbers bigger than 8 already satisfied the >=3 criteria.  Swapped them round and it should work now.

**Comment by andrewcharlton** [comment]
:+1: Well done!

:star: Trolls get very confused by zero and negative numbers, and tend to say 'Urgh'.  Amend your code and add tests to check for this.

**Comment by andrewcharlton** [comment]
:+1: Excellent!

**Pull request closed without merging**
